const h1=document.createElement('h1')
const p=document.createElement('p')
const strong=document.createElement('strong')
const em=document.createElement('em')
const a=document.createElement('a')
a.href='https://developer.mozilla.org/en-US/docs/Web/HTML'
const table=document.createElement('table')
const body=document.querySelector("body")
p.appendChild(strong)
p.appendChild(em)
p.appendChild(a)
body.appendChild(table)
body.appendChild(h1)
body.appendChild(p)